name: platonic_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy<2.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - requests>=2.25.0
  - tqdm>=4.62.0
  - pip
  - pip:
    - python-dotenv>=0.19.0